// Biome palettes. Each biome supplies a palette used across all visual layers.
// The renderer blends two biomes (current and next) using world.biomeBlend
// so transitions are seamless.

import type { BiomeId } from "./types";
import { hexToRgb, type RGB } from "./colors";

export interface BiomePalette {
  id: BiomeId;
  label: string;
  // Sky stops, ordered top→bottom
  skyTop: RGB;
  skyMid: RGB;
  skyBottom: RGB;
  // Mountain layers, far→near
  mountainsFar: RGB;
  mountainsMid: RGB;
  mountainsNear: RGB;
  // Ground / road shoulder
  ground: RGB;
  road: RGB;
  roadLine: RGB;
  // Foreground silhouettes (trees, cacti, buildings) base color
  fgSilhouette: RGB;
  // Accent lights (windows, neon)
  accent: RGB;
  // Foreground type used by the midground layer
  scenery:
    | "cactus"
    | "pine"
    | "city"
    | "ruins"
    | "rocks"
    | "neon_city"
    | "japan"
    | "alien"
    | "kelp"
    | "lava"
    | "floating"
    | "moon"
    | "mega"
    | "glitch";
  fogDensity: number; // 0..1 base fog
}

const P = (hex: string) => hexToRgb(hex);

export const BIOMES: Record<BiomeId, BiomePalette> = {
  desert: {
    id: "desert",
    label: "Sun-bleached Desert",
    skyTop: P("#f5b58a"),
    skyMid: P("#f4d29a"),
    skyBottom: P("#fbe7c2"),
    mountainsFar: P("#9a6b6f"),
    mountainsMid: P("#7c4f55"),
    mountainsNear: P("#583b3f"),
    ground: P("#c89a66"),
    road: P("#2a2326"),
    roadLine: P("#f3d189"),
    fgSilhouette: P("#3a2a2a"),
    accent: P("#ffb86b"),
    scenery: "cactus",
    fogDensity: 0.05,
  },
  snowy: {
    id: "snowy",
    label: "Snowy Mountains",
    skyTop: P("#7e8fb3"),
    skyMid: P("#b6c8de"),
    skyBottom: P("#dee7f1"),
    mountainsFar: P("#7d8ba1"),
    mountainsMid: P("#5b6a82"),
    mountainsNear: P("#3a465c"),
    ground: P("#e9eef5"),
    road: P("#262a31"),
    roadLine: P("#f7faff"),
    fgSilhouette: P("#1f2630"),
    accent: P("#bcd4ff"),
    scenery: "pine",
    fogDensity: 0.18,
  },
  cyberpunk: {
    id: "cyberpunk",
    label: "Neon Cyberpunk",
    skyTop: P("#1a0a2a"),
    skyMid: P("#3a0f55"),
    skyBottom: P("#7a1a6a"),
    mountainsFar: P("#1c0a30"),
    mountainsMid: P("#250a3a"),
    mountainsNear: P("#0d0418"),
    ground: P("#150a22"),
    road: P("#0a0612"),
    roadLine: P("#ff3df0"),
    fgSilhouette: P("#0b0518"),
    accent: P("#ff3df0"),
    scenery: "neon_city",
    fogDensity: 0.22,
  },
  rain_highway: {
    id: "rain_highway",
    label: "Rainy Highway",
    skyTop: P("#33384a"),
    skyMid: P("#4d5364"),
    skyBottom: P("#697283"),
    mountainsFar: P("#3d4456"),
    mountainsMid: P("#2a3040"),
    mountainsNear: P("#1d2230"),
    ground: P("#2c2f38"),
    road: P("#13151b"),
    roadLine: P("#dcdde2"),
    fgSilhouette: P("#0e1018"),
    accent: P("#8acaff"),
    scenery: "city",
    fogDensity: 0.3,
  },
  forest: {
    id: "forest",
    label: "Whispering Forest",
    skyTop: P("#244238"),
    skyMid: P("#3e6a55"),
    skyBottom: P("#82a98a"),
    mountainsFar: P("#1c3a32"),
    mountainsMid: P("#10261f"),
    mountainsNear: P("#081511"),
    ground: P("#1d3325"),
    road: P("#1a1814"),
    roadLine: P("#e3dabf"),
    fgSilhouette: P("#04100a"),
    accent: P("#f6f1c9"),
    scenery: "pine",
    fogDensity: 0.28,
  },
  wasteland: {
    id: "wasteland",
    label: "Abandoned Wasteland",
    skyTop: P("#5b4a3e"),
    skyMid: P("#a78b6e"),
    skyBottom: P("#d6b58a"),
    mountainsFar: P("#5a463a"),
    mountainsMid: P("#3a2c25"),
    mountainsNear: P("#1d1612"),
    ground: P("#7a6041"),
    road: P("#1a1612"),
    roadLine: P("#b89360"),
    fgSilhouette: P("#170f0a"),
    accent: P("#f0a96a"),
    scenery: "ruins",
    fogDensity: 0.4,
  },
  retro80s: {
    id: "retro80s",
    label: "Retro 80s City",
    skyTop: P("#1d0a3a"),
    skyMid: P("#a52e8a"),
    skyBottom: P("#ff7e3a"),
    mountainsFar: P("#3a0f55"),
    mountainsMid: P("#220a3a"),
    mountainsNear: P("#0c0418"),
    ground: P("#1d0a3a"),
    road: P("#0a0612"),
    roadLine: P("#ffe156"),
    fgSilhouette: P("#0b0518"),
    accent: P("#ff5fa2"),
    scenery: "city",
    fogDensity: 0.18,
  },
  alien: {
    id: "alien",
    label: "Alien World",
    skyTop: P("#2c0a40"),
    skyMid: P("#5a1c8a"),
    skyBottom: P("#cb7bff"),
    mountainsFar: P("#3b1356"),
    mountainsMid: P("#240a3c"),
    mountainsNear: P("#10061d"),
    ground: P("#3a1058"),
    road: P("#180524"),
    roadLine: P("#c4ff5a"),
    fgSilhouette: P("#10031c"),
    accent: P("#7dff9f"),
    scenery: "alien",
    fogDensity: 0.2,
  },
  underwater: {
    id: "underwater",
    label: "Sunken Highway",
    skyTop: P("#04293f"),
    skyMid: P("#0a4d6e"),
    skyBottom: P("#1a7a96"),
    mountainsFar: P("#073449"),
    mountainsMid: P("#04212f"),
    mountainsNear: P("#01121c"),
    ground: P("#0a3a4a"),
    road: P("#03161e"),
    roadLine: P("#a6e9ff"),
    fgSilhouette: P("#02101a"),
    accent: P("#a6e9ff"),
    scenery: "kelp",
    fogDensity: 0.5,
  },
  volcanic: {
    id: "volcanic",
    label: "Volcanic Plains",
    skyTop: P("#190a14"),
    skyMid: P("#5a1a1a"),
    skyBottom: P("#ff5a2a"),
    mountainsFar: P("#3d1414"),
    mountainsMid: P("#220a0a"),
    mountainsNear: P("#0c0303"),
    ground: P("#1c0a0a"),
    road: P("#0a0303"),
    roadLine: P("#ffb056"),
    fgSilhouette: P("#080202"),
    accent: P("#ff7a2a"),
    scenery: "lava",
    fogDensity: 0.32,
  },
  floating_islands: {
    id: "floating_islands",
    label: "Floating Islands",
    skyTop: P("#9bc4ff"),
    skyMid: P("#cfe6ff"),
    skyBottom: P("#fff1d6"),
    mountainsFar: P("#7e95b8"),
    mountainsMid: P("#5b6e8b"),
    mountainsNear: P("#3a4a64"),
    ground: P("#7a8a9b"),
    road: P("#23262d"),
    roadLine: P("#fff5d6"),
    fgSilhouette: P("#101620"),
    accent: P("#ffd07a"),
    scenery: "floating",
    fogDensity: 0.18,
  },
  ruins: {
    id: "ruins",
    label: "Post-apocalyptic Ruins",
    skyTop: P("#322a30"),
    skyMid: P("#5a4a4a"),
    skyBottom: P("#8a7062"),
    mountainsFar: P("#3a3236"),
    mountainsMid: P("#241e22"),
    mountainsNear: P("#100c0e"),
    ground: P("#2a2424"),
    road: P("#0d0a0a"),
    roadLine: P("#7a6850"),
    fgSilhouette: P("#070406"),
    accent: P("#d2925a"),
    scenery: "ruins",
    fogDensity: 0.35,
  },
  night_highway: {
    id: "night_highway",
    label: "Endless Night Highway",
    skyTop: P("#04060e"),
    skyMid: P("#0a1024"),
    skyBottom: P("#1a2540"),
    mountainsFar: P("#0a1024"),
    mountainsMid: P("#070a18"),
    mountainsNear: P("#03050c"),
    ground: P("#0a0c14"),
    road: P("#02030a"),
    roadLine: P("#f5e7a0"),
    fgSilhouette: P("#02020a"),
    accent: P("#9fc8ff"),
    scenery: "city",
    fogDensity: 0.16,
  },
  vaporwave: {
    id: "vaporwave",
    label: "Vaporwave Sunset Coast",
    skyTop: P("#2a0a55"),
    skyMid: P("#a13a99"),
    skyBottom: P("#ff9ad0"),
    mountainsFar: P("#3a1a6a"),
    mountainsMid: P("#241048"),
    mountainsNear: P("#10052a"),
    ground: P("#2a0e55"),
    road: P("#0a0418"),
    roadLine: P("#5af0ff"),
    fgSilhouette: P("#0a0418"),
    accent: P("#5af0ff"),
    scenery: "city",
    fogDensity: 0.18,
  },
  japan_country: {
    id: "japan_country",
    label: "Japanese Countryside",
    skyTop: P("#7d92b8"),
    skyMid: P("#c2cfdc"),
    skyBottom: P("#f4dbe4"),
    mountainsFar: P("#7587a5"),
    mountainsMid: P("#4f6080"),
    mountainsNear: P("#2c3a52"),
    ground: P("#6a8a5a"),
    road: P("#1d1d22"),
    roadLine: P("#fff5d6"),
    fgSilhouette: P("#0c1014"),
    accent: P("#ff7da3"),
    scenery: "japan",
    fogDensity: 0.22,
  },
  moon: {
    id: "moon",
    label: "Moon Surface",
    skyTop: P("#020208"),
    skyMid: P("#04060f"),
    skyBottom: P("#0a0e1c"),
    mountainsFar: P("#1a1d26"),
    mountainsMid: P("#0e1018"),
    mountainsNear: P("#05060c"),
    ground: P("#7d7e85"),
    road: P("#3a3a40"),
    roadLine: P("#dadbe0"),
    fgSilhouette: P("#1c1d22"),
    accent: P("#a0c8ff"),
    scenery: "moon",
    fogDensity: 0.05,
  },
  megacity: {
    id: "megacity",
    label: "Futuristic Megacity",
    skyTop: P("#0a0e22"),
    skyMid: P("#1c2150"),
    skyBottom: P("#3c4d96"),
    mountainsFar: P("#0a1230"),
    mountainsMid: P("#06091e"),
    mountainsNear: P("#03050c"),
    ground: P("#0a0c18"),
    road: P("#04060e"),
    roadLine: P("#7be0ff"),
    fgSilhouette: P("#02030a"),
    accent: P("#7be0ff"),
    scenery: "mega",
    fogDensity: 0.22,
  },
  glitch: {
    id: "glitch",
    label: "Glitch Dimension",
    skyTop: P("#0d000d"),
    skyMid: P("#3d0040"),
    skyBottom: P("#ff00aa"),
    mountainsFar: P("#1d001d"),
    mountainsMid: P("#2a002a"),
    mountainsNear: P("#080008"),
    ground: P("#100010"),
    road: P("#020002"),
    roadLine: P("#00ffd5"),
    fgSilhouette: P("#020002"),
    accent: P("#00ffd5"),
    scenery: "glitch",
    fogDensity: 0.2,
  },
};

export const BIOME_LIST: BiomeId[] = Object.keys(BIOMES) as BiomeId[];
